// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Bootstrap():Promise<model.AppState>;

export function Browse(arg1:string):Promise<model.Directory>;

export function CancelDownload(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<model.ConnectionState>;

export function OpenLocalPath(arg1:string):Promise<void>;

export function PickDefaultDownloadDir():Promise<string>;

export function PickDownloadLocation(arg1:string):Promise<string>;

export function SetDefaultDownloadDir(arg1:string):Promise<model.Settings>;

export function StartDownload(arg1:model.DownloadRequest):Promise<model.DownloadTask>;
