// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function Browse(arg1) {
  return window['go']['main']['App']['Browse'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function OpenLocalPath(arg1) {
  return window['go']['main']['App']['OpenLocalPath'](arg1);
}

export function PickDefaultDownloadDir() {
  return window['go']['main']['App']['PickDefaultDownloadDir']();
}

export function PickDownloadLocation(arg1) {
  return window['go']['main']['App']['PickDownloadLocation'](arg1);
}

export function SetDefaultDownloadDir(arg1) {
  return window['go']['main']['App']['SetDefaultDownloadDir'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
